#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory

#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

application=`getApplication`

runApplication blockMesh
cp -r 0.orig 0
runApplication setFields
runApplication $application