#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

application=`getApplication`

runApplication blockMesh
cp -r 0.orig 0
runApplication setFields
runApplication $application
